Repository hebertcisco/nest-sns, pull requests merged in 2023-03, with the labels that each got.

#124 Merge dependencies into Develop
  package-lock.json
  package.json
Labels: dependencies

#168 Merge dependencies into Develop
  package-lock.json
  package.json
Labels: dependencies

#179 #175 - Fix: Adjusted OS and CPU values
  package.json
Labels: enhancement, good first issue

#180 #175 - Fix: Adjusted OS and CPU values #179
  package-lock.json
  package.json
Labels: enhancement
