Repository hebertcisco/nest-sns, pull requests merged in 2023-01, with the labels that each got.

#9 chore() Merge dependencies from develop to main
  README.md
  package-lock.json
  package.json
Labels: dependencies

#10 fixed export of modules and help structure of files
  .gitpod.yml
  .npmignore
  .release-it.json
  lib/index.ts
  lib/interfaces/index.ts
  lib/modules/index.ts
  lib/modules/sms/contract/index.ts
  lib/modules/sms/contract/types/index.ts
  lib/modules/sms/contract/types/sms.types.ts
  lib/modules/sms/index.ts
  lib/modules/sms/services/index.ts
  lib/modules/sms/services/sms.service.ts
  lib/modules/sns/common/constants/index.ts
  lib/modules/sns/common/constants/sns.constants.ts
  lib/modules/sns/common/index.ts
  lib/modules/sns/common/testing/fixtures.ts
  lib/modules/sns/common/testing/index.ts
  lib/modules/sns/contract/index.ts
  lib/modules/sns/contract/interfaces/index.ts
  lib/modules/sns/contract/interfaces/sns-module.interfaces.ts
  lib/modules/sns/contract/types/index.ts
  lib/modules/sns/contract/types/sns.types.ts
  lib/modules/sns/index.ts
  lib/modules/sns/services/__tests__/sns.service.spec.ts
  lib/modules/sns/services/index.ts
  lib/modules/sns/services/sns.service.ts
  lib/modules/sns/sns.module.ts
  lib/sns.module.ts
  lib/types/index.ts
  package-lock.json
  package.json
Labels: bug, dependencies

#11 (feat/add-docs) Add documentation for SmsService and SnsModule
  README.md
  docs/sms/sms.service.md
  docs/sns/sns.module.md
  docs/sns/sns.service.md
  docsify/sidebar.md
  index.html
  package-lock.json
  package.json
Labels: documentation

#12 (feat/add-docs) Add documentation for SmsService and SnsModule
  README.md
  docs/sms/sms.service.md
  docs/sns/sns.module.md
  docs/sns/sns.service.md
  docsify/sidebar.md
  index.html
  package-lock.json
  package.json
Labels: documentation

#23 chore() Merge dependencies from develop to main
  package-lock.json
  package.json
Labels: dependencies
